[appsync] Add missing sys/time.h include for APP_SYNC_DBUS
Fixes the following:

  /usr/bin/ld: usb_moded-usb_moded-appsync.o: in function `appsync_enumerate_usb':
  usb_moded-appsync.c:(.text+0x1db): undefined reference to `timersub'